STATES = [
 "California (CA)",
 "Colorado (CO)",
 "Connecticut(CT)",
 "Delaware (DE)",
 "Florida (FL)",
 "Georgia (GA)",
 "Hawaii (HI)",
 "Idaho (ID)",
 "Illinois (IL)",
 "Indiana (IN)",
 "Iowa (IA)",
 "Kansas (KS)",
 "Kentucky (KY)",
 "Louisiana (LA)",
 "Maine (ME)",
 "Maryland (MD)",
 "Massachusetts (MA)",
 "Michigan (MI)",
 "Minnesota (MN)",
 "Mississippi (MS)",
 "Missouri (MO)",
 "Montana (MT)",
 "Nebraska (NE)",
 "Nevada (NV)",
 "New Hampshire (NH)",
 "New Jersey (NJ)",
 "New Mexico (NM)",
 "New York (NY)",
 "North Carolina (NC)",
 "North Dakota (ND)",
 "Ohio (OH)",
 "Oklahoma (OK)",
 "Oregon (OR)",
 "Pennsylvania (PA)",
 "Rhode Island (RI)",
 "South Carolina (SC)",
 "South Dakota (SD)",
 "Tennessee (TN)",
 "Texas (TX)",
 "Utah (UT)",
 "Vermont (VT)",
 "Virginia (VA)",
 "Washington (WA)",
 "West Virginia (WV)",
 "Wisconsin (WI)",
 "Wyoming (WY)",
 "Other - Outside of US (NA)"
]


LIST = [
	{label: "California (CA)", value: "CA"},
	{label: "Colorado (CO)", value: "CO"},
	{label: "Connecticut(CT)", value: "CT"},
	{label: "Delaware (DE)", value: "DE"},
	{label: "Florida (FL)", value: "FL"},
	{label: "Georgia (GA)", value: "GA"},
	{label: "Hawaii (HI)", value: "HI"},
	{label: "Idaho (ID)", value: "ID"},
	{label: "Illinois (IL)", value: "IL"},
	{label: "Indiana (IN)", value: "IN"},
	{label: "Iowa (IA)", value: "IA"},
	{label: "Kansas (KS)", value: "KS"},
	{label: "Kentucky (KY)", value: "KY"},
	{label: "Louisiana (LA)", value: "LA"},
	{label: "Maine (ME)", value: "ME"},
	{label: "Maryland (MD)", value: "MD"},
	{label: "Massachusetts (MA)", value: "MA"},
	{label: "Michigan (MI)", value: "MI"},
	{label: "Minnesota (MN)", value: "MN"},
	{label: "Mississippi (MS)", value: "MS"},
	{label: "Missouri (MO)", value: "MO"},
	{label: "Montana (MT)", value: "MT"},
	{label: "Nebraska (NE)", value: "NE"},
	{label: "Nevada (NV)", value: "NV"},
	{label: "New Hampshire (NH)", value: "NH"},
	{label: "New Jersey (NJ)", value: "NJ"},
	{label: "New Mexico (NM)", value: "NM"},
	{label: "New York (NY)", value: "NY"},
	{label: "North Carolina (NC)", value: "NC"},
	{label: "North Dakota (ND)", value: "ND"},
	{label: "Ohio (OH)", value: "OH"},
	{label: "Oklahoma (OK)", value: "OK"},
	{label: "Oregon (OR)", value: "OR"},
	{label: "Pennsylvania (PA)", value: "PA"},
	{label: "Rhode Island (RI)", value: "RI"},
	{label: "South Carolina (SC)", value: "SC"},
	{label: "South Dakota (SD)", value: "SD"},
	{label: "Tennessee (TN)", value: "TN"},
	{label: "Texas (TX)", value: "TX"},
	{label: "Utah (UT)", value: "UT"},
	{label: "Vermont (VT)", value: "VT"},
	{label: "Virginia (VA)", value: "VA"},
	{label: "Washington (WA)", value: "WA"},
	{label: "West Virginia (WV)", value: "WV"},
	{label: "Wisconsin (WI)", value: "WI"},
	{label: "Wyoming (WY)", value: "WY"},
	{label: "Other - Outside of US", value: "NA"}
]